#!/usr/bin/env node

const { requireConfig } = require('@datawrapper/backend-utils');
const { initORM } = require('@datawrapper/orm');
const config = requireConfig();

initORM(config).then(function({ db }) {
	const task = process.argv[2];
	const sub = process.argv[3] || false;

	const mod = require(`../src/tasks/${task}`);

	if (sub) mod[sub](); else mod();

	setTimeout(() => {
	    db.close();
	}, 100);
});

