version: "3.5"
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test

  redis:
    image: "redis:6.0.5-alpine3.12"
    command: redis-server --appendonly yes
    expose:
      - "6379"

  node:
    build:
      context: ./test
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - "../..:/app"

networks:
  default:
    driver: overlay
    attachable: true
