version: "3.5"
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    expose:
      - 3306
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test

  redis:
    image: "redis:6.0.5-alpine3.12"
    command: redis-server --appendonly yes
    expose:
      - "6379"

  opensearch-node1:
    image: "opensearchproject/opensearch:1.2.0"
    expose:
      - 9200
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
      - logger.level=WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9200 | grep -q 'HTTP/1.1 200'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  opensearch-setup:
    image: "node:18"
    depends_on:
      opensearch-node1:
        condition: service_healthy
    volumes:
      - "../..:/app:ro"
    entrypoint: >
      sh -c '
      curl -X PUT http://opensearch-node1:9200/_template/logstash -H "Content-Type: application/json" -d @/app/services/logstash/template/charts.json;
      exit 0;
      '

  node:
    build:
      context: ./test
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      opensearch-setup:
        condition: service_started
    volumes:
      - "../..:/app"

networks:
  default:
    driver: overlay
    attachable: true
